### ISSUE TITLE
Not able to see the images generated

### ISSUE THREAD

**Issue by himanshu1315sharma** [pratham-jaiswal/two-wheeler-traffic-rule-violation#1]
i followed your instructions but i am not able see images in violation folder can you tell me what m i missing here i cloned your master branch here

**Comment by pratham-jaiswal** [comment]
do you mind posting a screenshot of terminal and directory tree?

Your directory should look something like this:
```
two-wheeler-traffic-rule-violation-main
├───Violations
│   ├───02-12-2023
│   │   ├───186130975 - wrong_lane - 01-12-2023 13 04 42
│   │   └───30X11962 - no_helmet - 30-11-2023 22 00 59
├───main.py
├───input.mp4
└───.env
```

When you run the main.py your terminal should look like this:
```.sh
loading Roboflow workspace...
loading Roboflow project...
loading Roboflow workspace...
loading Roboflow project...
loading Roboflow workspace...
loading Roboflow project...
Processing frames:   1%|▋                                                                    | 1/95 [00:20<31:54, 20.36s/frames]
```

make sure you have created a .env file with variables as:
```.env
OCR_SPACE_API=YOUR_OCRSPACE_API_KEY
ROBOFLOW_API_KEY=YOUR_ROBOFLOW_API_KEY  
```

Also, is there any internal folders being created in the violations folder such as `02-12-2023` (current date) with child folders as `186130975 - wrong_lane - 01-12-2023 13 04 42` (license plate number with violation and date time)? As this folder will contain the images regarding this particular two-wheeler.

**Comment by himanshu1315sharma** [comment]
sure here it is 
![two-wheeler](https://github.com/pratham-jaiswal/two-wheeler-traffic-rule-violation/assets/124361184/64e014c8-ce5f-47e2-b1c2-d9d6b399ac7c)
![image](https://github.com/pratham-jaiswal/two-wheeler-traffic-rule-violation/assets/124361184/4c20dbe2-7e06-4c36-aad0-4f5fb9b87eb2)

**Comment by pratham-jaiswal** [comment]
try another video, I believe it's not detecting any two wheelers in the video used.
also you can increase the number of frames to check
Here, I'm checking for every 180th frame
```py
for frame_number in tqdm(range(0, total_frames, 180), desc="Processing frames", unit="frames")
```
You can drop it to 10 or any number you like, if you believe there are two wheelers in the video.
```py
nth_frame = 10
for frame_number in tqdm(range(0, total_frames, nth_frame), desc="Processing frames", unit="frames")
```

**Comment by himanshu1315sharma** [comment]
Can you send me the video that you've used here I guess then it would be more clearer if the model is working fine or not

**Comment by pratham-jaiswal** [comment]
I tested it on a youtube video, but right now I can't find it on youtube so you can download from [here](https://mega.nz/file/A0BhRaTD#cp8jci_9nq2W42Z5j1W6tmzeKtPJDaTkt-Mjxtv_AGs). Although, I would say get/record a clearer video where license plate is at least human readable.

**Comment by himanshu1315sharma** [comment]
yes now it is working thanks pratham
